"""initial_models

Revision ID: e847da35e993
Revises: 
Create Date: 2026-03-29 23:50:48.302927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e847da35e993'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('venue_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('layouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('canvas_width', sa.Integer(), nullable=False),
    sa.Column('canvas_height', sa.Integer(), nullable=False),
    sa.Column('zoom_level', sa.Float(), nullable=False),
    sa.Column('pan_x', sa.Float(), nullable=False),
    sa.Column('pan_y', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('layout_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shape', sa.Enum('round', 'rectangle', 'sweetheart', name='table_shape', create_constraint=True), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_layout_id'), 'tables', ['layout_id'], unique=False)
    op.create_table('venue_features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('layout_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('dance_floor', 'bar', 'cake_table', 'stage', 'custom', name='venue_feature_type', create_constraint=True), nullable=False),
    sa.Column('shape', sa.Enum('rectangle', 'circle', name='venue_feature_shape', create_constraint=True), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_features_layout_id'), 'venue_features', ['layout_id'], unique=False)
    op.create_table('guests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('meal_preference', sa.String(length=100), nullable=True),
    sa.Column('is_plus_one', sa.Boolean(), nullable=False),
    sa.Column('plus_one_of', sa.UUID(), nullable=True),
    sa.Column('group_tag', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('table_id', sa.UUID(), nullable=True),
    sa.Column('seat_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plus_one_of'], ['guests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_event_id'), 'guests', ['event_id'], unique=False)
    op.create_index(op.f('ix_guests_table_id'), 'guests', ['table_id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('seat_index', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('x_offset', sa.Float(), nullable=False),
    sa.Column('y_offset', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seats_table_id'), 'seats', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seats_table_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_guests_table_id'), table_name='guests')
    op.drop_index(op.f('ix_guests_event_id'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_venue_features_layout_id'), table_name='venue_features')
    op.drop_table('venue_features')
    op.drop_index(op.f('ix_tables_layout_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_table('layouts')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
